language: ruby
cache: bundler
sudo: false
rvm:
  - 2.4.0
  - 2.3.3
  - 2.2.6
  - jruby-9.0.5.0
  - rbx-2
gemfile:
  - gemfiles/ar50.gemfile
matrix:
  allow_failures:
    - rvm: jruby-9.0.5.0
    - rvm: rbx-2
